### ISSUE TITLE
Invalid Function xcb:+request

### ISSUE THREAD

**Issue by Vannil** [ch11ng/xelb#9] opened 2016-03-10 12:24 UTC
This seems to be a problem only on Emacs 25.
After installing the package from ELPA, whenever
`xcb:+request` is used, the `invalid-function` error is
signaled.
I tried this on Emacs 24.4 too, and nothing happens there.

**Comment by ch11ng** [comment] 2016-03-10 14:03
Is XELB installed from Emacs 25? The byte code generated by Emacs 24 might not be compatible with Emacs 25.  Or what if you call `xcb:-+request`?

**Comment by Vannil** [comment] 2016-03-10 19:39
I compiled the library in a fresh installation of Emacs 25.0.92.
With `xcb:-+request` everything is fine, there are only some
indentation issues.

**Comment by ch11ng** [comment] 2016-03-11 04:28
`xcb:+request` is merely a macro wrapping around `xcb:-+request`.  So do other macros defined in xcb.el available? Maybe this library is loaded within an `eval-when-compile` form?

**Comment by Vannil** [comment] 2016-03-12 13:29
I did some more testing and I'm getting different results each time.
Sometimes it works fine, sometimes it gives this error, sometimes
a different one (that normally never happens).
What I do is `require`-ing the library at top-level, without any wrapper
like `eval-when-compile` and the like, then use it as needed.
I don't think it has to do with the current Emacs configuration, since I
tested it with the default config (I just removed the toolbar and the menu).
I should probably note that I did these tests in different environments,
in case it happens to be relevant: I tried it on GNOME, Xfce, and a
bare Emacs over X.
In all cases though, Emacs was compiled without any particular toolkit, just
Xlib/XCB.

**Comment by ch11ng** [comment] 2016-03-12 14:33
What about starting Emacs with `emacs -Q`, then adding the `load-path` and doing `(require 'xcb)` manually?

**Comment by Vannil** [comment] 2016-03-12 19:31
Doing that seems to cause no errors.
I did find out that installing the package from ELPA also
installs the `cl-generic-0.2` package, that sometimes
causes errors with how the object orientation is implemented
in Emacs 25.
Besides this unrelated discovery, it seems to work fine.
I'm starting to doubt it's something with XELB, but I had this kind
of problem only with it and cl-generic.

**Comment by ch11ng** [comment] 2016-03-13 01:13
> I did find out that installing the package from ELPA also
> installs the cl-generic-0.2 package, that sometimes
> causes errors with how the object orientation is implemented
> in Emacs 25.

`cl-generic-0.2` is installed due to a bug in Emacs.  But it should be irrelevant to this issue since `xcb:+request` is a simple macro rather than some EIEIO stuff.

Again, have you tried other macros defined in xcb.el such as `xcb:+request-checked` and `xcb:+reply`?  And what does <kbd>C-h o</kbd> say about them?

**Comment by Vannil** [comment] 2016-03-13 17:34
It seems to be an issue only with `xcb:+request`,
I didn't get any particular error with the others.
Using <kbd>C-h o</kbd> shows their documentation.

**Comment by ch11ng** [comment] 2016-03-14 05:14
> It seems to be an issue only with `xcb:+request`,
> I didn't get any particular error with the others.
> Using <kbd>C-h o</kbd> shows their documentation.

What does <kbd>C-h o xcb:+request RET</kbd> show? Does `xcb:+request` get redefined or is it simply unbound? And could you provide minimal init file / code to reproduce this issue? FYI I've tested on emacs-25 (commit 80ec484a) GTK3 and Lucid build.

**Comment by Vannil** [comment] 2016-03-15 20:43
Using <kbd>C-h o xcb:+request RET</kbd> shows the documentation,
like when using <kbd>C-h f</kbd>.
I noticed the errors occurs more often in callbacks,
e.g. during event handling.
As a minimal code to reproduce it, you could try with

```
(setq connection (xcb:connect-to-socket))
;; [...]
(xcb:+event connection
  'xcb:Expose
  (lambda (a b)
    (let ((r (xcb:+request connection
                 (make-instance 'xcb:QueryFont
                                :font fid))))
      (print (xcb:+reply connection r t)))))
```

The code I used when this error happened is more complex,
but it works the same way.

**Comment by ch11ng** [comment] 2016-03-16 05:23
I modified your code to make it working:

``` elisp
(setq connection (xcb:connect-to-socket))
(xcb:+event connection 'xcb:Expose
            (lambda (a b)
              (let ((r (xcb:+request connection
                           (make-instance 'xcb:QueryFont
                                          :font 0))))
                (print (xcb:+reply connection r)))))
(xcb:+request connection
    (make-instance 'xcb:ChangeWindowAttributes
                   :window #x1c00004
                   :value-mask xcb:CW:EventMask
                   :event-mask xcb:EventMask:Exposure))
(xcb:flush connection)
```

But there's still no error.  In fact, my another project EXWM is full of callbacks, and I've never experienced such problem.

Can you reproduce this issue without byte-compiling the source? If so, you can retrieve more verbose message by setting `xcb:debug-on` to `t`; maybe it will provide something useful.

**Comment by Vannil** [comment] 2016-03-17 17:41
The error happens even if I evaluate each file without
compiling them.
After setting `xcb:debug-on` to `t`, the message log
showed that the error happened when dealing
with drawing requests, like `xcb:PolyRectangle`.

**Comment by ch11ng** [comment] 2016-03-18 10:50
> After setting `xcb:debug-on` to `t`, the message log
> showed that the error happened when dealing
> with drawing requests, like `xcb:PolyRectangle`.

This request has nothing special.  I think there must be something more useful in the log.  Could you provide the full log, probably also with `debug-on-error` enabled, as a Gist?

**Comment by Vannil** [comment] 2016-03-22 12:15
I apologize for the late reply.
https://gist.github.com/Vannil/164919cd350a81e98e46 is
the gist with two logs.
The first is a part of the full log that shows the `invalid-function` message,
without `debug-on-error` enabled.
The second is the full log, after connecting, with `debug-on-error` enabled.

**Comment by ch11ng** [comment] 2016-03-23 05:51
When `debug-on-error` is non-nil, there should also be a `*Backtrace*` buffer.  What's the content?

**Comment by ch11ng** [comment] 2019-02-06 12:04
Sorry for revisiting this issue after so long a time.  I think I've encountered the problem for a few times myself, and what I did was to remove the byte-compiled files (I usually don't run XELB byte-compiled).  Perhaps there are some incompatibility issues between EIEIO and the backported layer.

I'm closing this issue now.  Please reopen it if you find this problem still there.

**Closed as completed by ch11ng** 2019-02-06 12:04 UTC
